name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Extrae el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configura Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3: Construye el proyecto con Maven
      - name: Build with Maven
        run: mvn clean package

      # Paso 4: Despliega la aplicación en Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ApiCandidateManagement' # Nombre de tu aplicación en Azure
          slot-name: 'production'           # Slot de despliegue (por defecto: production)
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # Perfil de publicación
          package: target/selectionProcess-0.0.1-SNAPSHOT.jar   # Ubicación del archivo .jar
